const BAD_REQUEST_ERROR = 400;
const NOT_FOUND_ERROR = 404;
const SUCCESS_ERROR = 200;
const CREATED_ERROR = 201;
const INCOMPLETE_REQUEST_ERROR = 500;
const CONFLICT_ERROR = 409;
const DUPLICATE_ERROR = 11000;
const AUTHENTICATION_ERROR = 401;

module.exports = {
  BAD_REQUEST_ERROR,
  NOT_FOUND_ERROR,
  SUCCESS_ERROR,
  CREATED_ERROR,
  INCOMPLETE_REQUEST_ERROR,
  CONFLICT_ERROR,
  DUPLICATE_ERROR,
  AUTHENTICATION_ERROR,
};
