const BAD_REQUEST_ERROR = 400;
const AUTHENTICATION_ERROR = 401;
const PERMISSION_ERROR = 403;
const NOT_FOUND_ERROR = 404;
const CONFLICT_ERROR = 409;
const SUCCESS = 200;
const CREATED = 201;
const INTERNAL_SERVER_ERROR = 500;
const DUPLICATE_ERROR = 11000;

module.exports = {
  BAD_REQUEST_ERROR,
  NOT_FOUND_ERROR,
  SUCCESS,
  CREATED,
  INTERNAL_SERVER_ERROR,
  CONFLICT_ERROR,
  DUPLICATE_ERROR,
  AUTHENTICATION_ERROR,
  PERMISSION_ERROR,
};
